<?php include __DIR__ . '/../header.html' ?>
<div class="container">
    <div class="row">
        <h3>Listagem de posts</h3>
        <a class="btn btn-primary" href="/posts/create">Novo post</a>
        <table class="table">
            <thead>
            <tr>
                <th>ID</th>
                <th>Title</th>
                <th>Ações</th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($posts as $post): ?>
                <tr>
                    <td><?php echo $post->getId(); ?></td>
                    <td><?php echo $post->getTitle(); ?></td>
                    <td>
                        <?php echo "<a href='/posts/{$post->getId()}/categories' class='btn btn-primary'>Categorias</a>"; ?> |
                        <?php echo "<a href='/posts/{$post->getId()}/edit' class='btn btn-success'>Editar</a>"; ?> |
                        <?php echo "<a href='/posts/{$post->getId()}/remove' class='btn btn-danger'>Excluir</a>"; ?>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>
<?php include __DIR__ . '/../footer.html' ?>
